"""
Stubs pour l'autocomplétion FreeCAD dans VS Code
Ce fichier définit les types et signatures des principales fonctions FreeCAD
"""

from typing import List, Tuple, Optional, Union, Any

# Types de base FreeCAD
class Vector:
    def __init__(self, x: float = 0, y: float = 0, z: float = 0): ...
    x: float
    y: float
    z: float
    Length: float
    def add(self, other: 'Vector') -> 'Vector': ...
    def sub(self, other: 'Vector') -> 'Vector': ...
    def cross(self, other: 'Vector') -> 'Vector': ...
    def dot(self, other: 'Vector') -> float: ...

class Placement:
    def __init__(self, base: Vector = None, rotation: 'Rotation' = None): ...
    Base: Vector
    Rotation: 'Rotation'

class Rotation:
    def __init__(self, axis: Vector = None, angle: float = 0): ...

class Matrix:
    def __init__(self): ...

# Document et objets
class DocumentObject:
    def __init__(self): ...
    Name: str
    Label: str
    Placement: Placement
    ViewObject: 'ViewObject'
    def touch(self) -> None: ...
    def purgeTouched(self) -> None: ...

class ViewObject:
    def __init__(self): ...
    Visibility: bool
    DisplayMode: str
    ShapeColor: Tuple[float, float, float]
    Transparency: int

class Document:
    def __init__(self): ...
    Name: str
    FileName: str
    Objects: List[DocumentObject]
    
    def addObject(self, object_type: str, name: str = None) -> DocumentObject: ...
    def removeObject(self, name: str) -> None: ...
    def getObject(self, name: str) -> Optional[DocumentObject]: ...
    def getObjectsByLabel(self, label: str) -> List[DocumentObject]: ...
    def recompute(self) -> None: ...
    def save(self) -> None: ...
    def saveAs(self, filename: str) -> None: ...
    def close(self) -> None: ...

# Module FreeCAD principal
class FreeCADModule:
    ActiveDocument: Optional[Document]
    Version: List[str]
    
    @staticmethod
    def newDocument(name: str = None) -> Document: ...
    
    @staticmethod
    def openDocument(filename: str) -> Document: ...
    
    @staticmethod
    def closeDocument(name: str) -> None: ...
    
    @staticmethod
    def setActiveDocument(name: str) -> None: ...
    
    @staticmethod
    def listDocuments() -> dict: ...

# Console
class Console:
    @staticmethod
    def PrintMessage(message: str) -> None: ...
    
    @staticmethod
    def PrintWarning(message: str) -> None: ...
    
    @staticmethod
    def PrintError(message: str) -> None: ...
    
    @staticmethod
    def PrintLog(message: str) -> None: ...

# Instanciation des modules principaux
App = FreeCADModule()
Console = Console()

# Fonctions utilitaires communes
def Vector(x: float = 0, y: float = 0, z: float = 0) -> Vector: ...
def Placement(base: Vector = None, rotation: Rotation = None) -> Placement: ...
def Rotation(axis: Vector = None, angle: float = 0) -> Rotation: ...

# Géométrie de base
class Part:
    class Shape:
        def __init__(self): ...
        Area: float
        Volume: float
        CenterOfMass: Vector
        BoundBox: 'BoundBox'
        
        def fuse(self, other: 'Shape') -> 'Shape': ...
        def cut(self, other: 'Shape') -> 'Shape': ...
        def common(self, other: 'Shape') -> 'Shape': ...
        def extrude(self, direction: Vector) -> 'Shape': ...
        def revolve(self, axis: Vector, angle: float) -> 'Shape': ...
    
    class Feature:
        def __init__(self): ...
        Shape: 'Part.Shape'
    
    @staticmethod
    def makeBox(length: float, width: float, height: float, 
                pnt: Vector = None, dir: Vector = None) -> 'Part.Shape': ...
    
    @staticmethod
    def makeCylinder(radius: float, height: float, 
                     pnt: Vector = None, dir: Vector = None) -> 'Part.Shape': ...
    
    @staticmethod
    def makeSphere(radius: float, pnt: Vector = None) -> 'Part.Shape': ...

class BoundBox:
    def __init__(self): ...
    XMin: float
    XMax: float
    YMin: float
    YMax: float
    ZMin: float
    ZMax: float
    XLength: float
    YLength: float
    ZLength: float

# Mesh
class Mesh:
    class Feature:
        def __init__(self): ...
        Mesh: 'Mesh.Mesh'
    
    class Mesh:
        def __init__(self): ...
        CountPoints: int
        CountFacets: int
        def addFacet(self, p1: Vector, p2: Vector, p3: Vector) -> None: ...

# Draft (2D)
class Draft:
    @staticmethod
    def makeWire(points: List[Vector], closed: bool = False) -> DocumentObject: ...
    
    @staticmethod
    def makeLine(p1: Vector, p2: Vector) -> DocumentObject: ...
    
    @staticmethod
    def makeCircle(radius: float, placement: Placement = None) -> DocumentObject: ...

# Sketcher
class Sketcher:
    class SketchObject:
        def __init__(self): ...
        def addGeometry(self, geometry) -> int: ...
        def addConstraint(self, constraint) -> int: ...
